{
	"id": "AVG-2788",
	"advisories": [
		{
			"id": "AVG-2788",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "High"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-2788"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2022-34265",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-34265"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "python-django"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"lt": "4.0.6-1"
					}
				],
				"fixed": [
					"4.0.6-1"
				]
			}
		}
	]
}
