{
	"id": "AVG-1412",
	"advisories": [
		{
			"id": "AVG-1412",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Low"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-1412"
				}
			]
		},
		{
			"id": "ASA-202101-12",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202101-12"
				}
			]
		},
		{
			"id": "ASA-202101-12",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202101-12"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2021-21236",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-21236"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "python-cairosvg"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"lt": "2.5.1-1"
					}
				],
				"fixed": [
					"2.5.1-1"
				]
			}
		}
	]
}
