{
	"id": "AVG-946",
	"advisories": [
		{
			"id": "AVG-946",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Critical"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-946"
				}
			]
		},
		{
			"id": "ASA-201904-3",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-201904-3"
				}
			]
		},
		{
			"id": "ASA-201904-3",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-201904-3"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2019-0220",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-0220"
				}
			]
		},
		{
			"id": "CVE-2019-0217",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-0217"
				}
			]
		},
		{
			"id": "CVE-2019-0215",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-0215"
				}
			]
		},
		{
			"id": "CVE-2019-0211",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-0211"
				}
			]
		},
		{
			"id": "CVE-2019-0197",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-0197"
				}
			]
		},
		{
			"id": "CVE-2019-0196",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-0196"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "apache"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"lt": "2.4.39-1"
					}
				],
				"fixed": [
					"2.4.39-1"
				]
			}
		}
	]
}
