{
	"id": "AVG-1092",
	"advisories": [
		{
			"id": "AVG-1092",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Critical"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-1092"
				}
			]
		},
		{
			"id": "ASA-202002-3",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202002-3"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2020-6416",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6416"
				}
			]
		},
		{
			"id": "CVE-2020-6415",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6415"
				}
			]
		},
		{
			"id": "CVE-2020-6414",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6414"
				}
			]
		},
		{
			"id": "CVE-2020-6413",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6413"
				}
			]
		},
		{
			"id": "CVE-2020-6412",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6412"
				}
			]
		},
		{
			"id": "CVE-2020-6411",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6411"
				}
			]
		},
		{
			"id": "CVE-2020-6410",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6410"
				}
			]
		},
		{
			"id": "CVE-2020-6409",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6409"
				}
			]
		},
		{
			"id": "CVE-2020-6408",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6408"
				}
			]
		},
		{
			"id": "CVE-2020-6406",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6406"
				}
			]
		},
		{
			"id": "CVE-2020-6405",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6405"
				}
			]
		},
		{
			"id": "CVE-2020-6404",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6404"
				}
			]
		},
		{
			"id": "CVE-2020-6403",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6403"
				}
			]
		},
		{
			"id": "CVE-2020-6402",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6402"
				}
			]
		},
		{
			"id": "CVE-2020-6401",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6401"
				}
			]
		},
		{
			"id": "CVE-2020-6400",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6400"
				}
			]
		},
		{
			"id": "CVE-2020-6399",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6399"
				}
			]
		},
		{
			"id": "CVE-2020-6398",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6398"
				}
			]
		},
		{
			"id": "CVE-2020-6397",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6397"
				}
			]
		},
		{
			"id": "CVE-2020-6396",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6396"
				}
			]
		},
		{
			"id": "CVE-2020-6395",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6395"
				}
			]
		},
		{
			"id": "CVE-2020-6394",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6394"
				}
			]
		},
		{
			"id": "CVE-2020-6393",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6393"
				}
			]
		},
		{
			"id": "CVE-2020-6392",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6392"
				}
			]
		},
		{
			"id": "CVE-2020-6391",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6391"
				}
			]
		},
		{
			"id": "CVE-2020-6390",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6390"
				}
			]
		},
		{
			"id": "CVE-2020-6389",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6389"
				}
			]
		},
		{
			"id": "CVE-2020-6388",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6388"
				}
			]
		},
		{
			"id": "CVE-2020-6387",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6387"
				}
			]
		},
		{
			"id": "CVE-2020-6385",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6385"
				}
			]
		},
		{
			"id": "CVE-2020-6382",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6382"
				}
			]
		},
		{
			"id": "CVE-2020-6381",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6381"
				}
			]
		},
		{
			"id": "CVE-2019-19926",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-19926"
				}
			]
		},
		{
			"id": "CVE-2019-19925",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-19925"
				}
			]
		},
		{
			"id": "CVE-2019-19923",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-19923"
				}
			]
		},
		{
			"id": "CVE-2019-19880",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-19880"
				}
			]
		},
		{
			"id": "CVE-2019-18197",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-18197"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "chromium"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"lt": "80.0.3987.87-1"
					}
				],
				"fixed": [
					"80.0.3987.87-1"
				]
			}
		}
	]
}
