{
	"id": "AVG-2616",
	"advisories": [
		{
			"id": "AVG-2616",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Medium"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-2616"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2021-44543",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-44543"
				}
			]
		},
		{
			"id": "CVE-2021-44542",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-44542"
				}
			]
		},
		{
			"id": "CVE-2021-44541",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-44541"
				}
			]
		},
		{
			"id": "CVE-2021-44540",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-44540"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "privoxy"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"le": "3.0.32-1"
					}
				]
			}
		}
	]
}
