{
	"id": "AVG-1167",
	"advisories": [
		{
			"id": "ASA-202005-12",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202005-12"
				}
			]
		},
		{
			"id": "AVG-1167",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "High"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-1167"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2020-6465",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6465"
				}
			]
		},
		{
			"id": "CVE-2020-6466",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6466"
				}
			]
		},
		{
			"id": "CVE-2020-6467",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6467"
				}
			]
		},
		{
			"id": "CVE-2020-6468",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6468"
				}
			]
		},
		{
			"id": "CVE-2020-6469",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6469"
				}
			]
		},
		{
			"id": "CVE-2020-6470",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6470"
				}
			]
		},
		{
			"id": "CVE-2020-6471",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6471"
				}
			]
		},
		{
			"id": "CVE-2020-6472",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6472"
				}
			]
		},
		{
			"id": "CVE-2020-6473",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6473"
				}
			]
		},
		{
			"id": "CVE-2020-6474",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6474"
				}
			]
		},
		{
			"id": "CVE-2020-6475",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6475"
				}
			]
		},
		{
			"id": "CVE-2020-6476",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6476"
				}
			]
		},
		{
			"id": "CVE-2020-6477",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6477"
				}
			]
		},
		{
			"id": "CVE-2020-6478",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6478"
				}
			]
		},
		{
			"id": "CVE-2020-6479",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6479"
				}
			]
		},
		{
			"id": "CVE-2020-6480",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6480"
				}
			]
		},
		{
			"id": "CVE-2020-6481",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6481"
				}
			]
		},
		{
			"id": "CVE-2020-6482",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6482"
				}
			]
		},
		{
			"id": "CVE-2020-6483",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6483"
				}
			]
		},
		{
			"id": "CVE-2020-6484",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6484"
				}
			]
		},
		{
			"id": "CVE-2020-6485",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6485"
				}
			]
		},
		{
			"id": "CVE-2020-6486",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6486"
				}
			]
		},
		{
			"id": "CVE-2020-6487",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6487"
				}
			]
		},
		{
			"id": "CVE-2020-6488",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6488"
				}
			]
		},
		{
			"id": "CVE-2020-6489",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6489"
				}
			]
		},
		{
			"id": "CVE-2020-6490",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6490"
				}
			]
		},
		{
			"id": "CVE-2020-6491",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-6491"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "chromium"
						},
						"affected": {
							"type": "pacman",
							"range": [
								{
									"lt": "83.0.4103.61-1"
								}
							],
							"fixed": [
								"83.0.4103.61-1"
							]
						}
					}
				]
			}
		}
	],
	"data_source": "arch"
}
