{
	"id": "AVG-2842",
	"advisories": [
		{
			"id": "AVG-2842",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Unknown"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-2842"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2022-1622",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-1622"
				}
			]
		},
		{
			"id": "CVE-2022-1623",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-1623"
				}
			]
		},
		{
			"id": "CVE-2022-2056",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2056"
				}
			]
		},
		{
			"id": "CVE-2022-2057",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2057"
				}
			]
		},
		{
			"id": "CVE-2022-2058",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2058"
				}
			]
		},
		{
			"id": "CVE-2022-2519",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2519"
				}
			]
		},
		{
			"id": "CVE-2022-2520",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2520"
				}
			]
		},
		{
			"id": "CVE-2022-2521",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2521"
				}
			]
		},
		{
			"id": "CVE-2022-2867",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2867"
				}
			]
		},
		{
			"id": "CVE-2022-2868",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2868"
				}
			]
		},
		{
			"id": "CVE-2022-2869",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2869"
				}
			]
		},
		{
			"id": "CVE-2022-2953",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-2953"
				}
			]
		},
		{
			"id": "CVE-2022-34526",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-34526"
				}
			]
		},
		{
			"id": "CVE-2022-3570",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-3570"
				}
			]
		},
		{
			"id": "CVE-2022-3597",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-3597"
				}
			]
		},
		{
			"id": "CVE-2022-3599",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-3599"
				}
			]
		},
		{
			"id": "CVE-2022-3627",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-3627"
				}
			]
		},
		{
			"id": "CVE-2022-3970",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-3970"
				}
			]
		},
		{
			"id": "CVE-2022-48281",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2022-48281"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "libtiff"
						},
						"affected": {
							"type": "pacman",
							"range": [
								{
									"le": "4.4.0-1"
								}
							]
						}
					}
				]
			}
		}
	],
	"data_source": "arch"
}
