{
	"id": "AVG-2026",
	"advisories": [
		{
			"id": "ASA-202106-41",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202106-41"
				}
			]
		},
		{
			"id": "AVG-2026",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Medium"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-2026"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2021-33203",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-33203"
				}
			]
		},
		{
			"id": "CVE-2021-33571",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-33571"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "python-django"
						},
						"affected": {
							"type": "pacman",
							"range": [
								{
									"lt": "3.2.4-1"
								}
							],
							"fixed": [
								"3.2.4-1"
							]
						}
					}
				]
			}
		}
	]
}
